SELECT TOP (1000) [customer_id]
      ,[username]
      ,[first_name]
      ,[last_name]
      ,[age]
      ,[email]
      ,[customer_password]
      ,[phone_number]
  FROM [Online_shopping].[dbo].[Customer]